<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\eVote360_Pro.Infrastructure\eVote360_Pro.Infrastructure.csproj" />
    <ProjectReference Include="..\eVote360_Pro.Application\eVote360_Pro.Application.csproj" />
    <ProjectReference Include="..\eVote360_Pro.Shared\eVote360_Pro.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.16" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
